name: Bootcamp 2020 urdu

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing Node
      run: actions/setup-node@v2-beta
      with:
        node-version: 12  

    - name: installing surge
      run: npm install --global surge
      
    - name: deploying using surge
       run: surge ./ bootcamp_atif.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      

